---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - debug:
      msg: "{{ wadmin_password }} {{ wadmin_username }} {{ wdomain_password }} {{ wdomain_username }} {{ wproductid }}"

