---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Get domain from hostname
    shell: echo "{{ inventory_hostname }}" | cut -d'.' -f 2,3
    register: domain

  - name: Show debug output
    debug:
      msg:
       - "inventory_hostname: {{ inventory_hostname }}"
       - "ip_address: {{ ip_address }}"
       - "domain: {{ domain.stdout }}"

  - name: Provision VM
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      name: "{{ inventory_hostname }}"
      folder: "{{ vmfolder }}"
      template: "template-ubuntu-16.04-64bit-8gb-v1.0"
      cluster: "{{ cluster }}"
      resource_pool: "{{ resource_pool }}"
      datacenter: "{{ datacenter }}"
      guest_id: "ubuntu64Guest"
      disk:
      - size_gb: 10
        type: "thin"
        datastore: "{{ datastore }}"
        autoselect_datastore: yes
      hardware:
        memory_mb: 1024
        num_cpus: 1
      networks:
      - name: "{{ network_name }}"
        ip: "{{ ip_address }}"
        device_type: "{{ device_type }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain.stdout }}"
        netmask: "{{ netmask }}"
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
      customization:
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
        domain: "{{ domain.stdout }}"
        hostName: "{{ inventory_hostname }}"
        computerName: "{{ inventory_hostname }}"
      wait_for_ip_address: yes
      validate_certs: no
      state: present
    register: vmstatus

  - debug:
      msg: "Deploy message is: {{ vmstatus }}"
