---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - vmware_guest:
     hostname: "{{ vcenter_hostname }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     folder: "{{ vmfolder }}"
     validate_certs: no
     state: present
     name: "{{ inventory_hostname }}"
     template: "template-ubuntu-16.04-64bit-8gb-v1.0"
     cluster: {{ cluster }}
     resource_pool: "{{ resource_pool }}"
     datacenter: "{{ datacenter }}"
     guest_id: "ubuntu64Guest"
     disk:
     - size_gb: 10
       type: "thin"
       autoselect_datastore: yes
       datastore: "{{ datastore }}"
     wait_for_ip_address: yes
     hardware:
       memory_mb: 1024
       num_cpus: 1
     networks:
     - name: "{{ network_name }}"
       ip: "{{ ip_address }}"
       device_type: "{{ device_type }}"
       gateway: "{{ gateway }}"
       domain: "{{ domain }}"
       netmask: "{{ netmask }}"
       dns_servers:
       - "{{ dns1 }}"
       - "{{ dns2 }}"
     customization:
       dns_servers:
       - "{{ dns1 }}"
       - "{{ dns2 }}"
       domain: "{{ domain }}"
       hostName: "{{ inventory_hostname }}"
       computerName: "{{ inventory_hostname }}"
    register: deploy
    ignore_errors: yes
