---
# ----------------------------------------------------------
# Provisions Windows VM(s) and creates DNS records
#
# AWX 1.0.5  v1.0.0
# ----------------------------------------------------------
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Get domain from hostname
    shell: echo "{{ inventory_hostname }}" | cut -d'.' -f 2,3
    register: domain

  - name: Provision VM
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      name: "{{ inventory_hostname }}"
      folder: "{{ vcenter_folder }}"
      template: "{{ vcenter_template }}"
      cluster: "{{ vcenter_cluster }}"
      resource_pool: "{{ vcenter_resource_pool }}"
      datacenter: "{{ vcenter_datacenter }}"
      guest_id: "{{ vcenter_guestos }}"
      disk:
      - size_gb: "{{ vm_diskgb }}"
        type: "thick"
        datastore: "{{ vcenter_datastore }}"
      networks:
      - name: "{{ network_name }}"
        ip: "{{ ip_address }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain.stdout }}"
        netmask: "{{ netmask }}"
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
      customization:
        domainadmin: "{{ domain_user }}"
        domainadminpassword: "{{ domain_pass }}"
        joindomain: "{{domain_name }}"
        orgname: "{{ org_name }}"
        password: "{{ admin_pass }}"
        productid: "{{ product_id }}"
        runonce: "{{ cmds_to_run }}"
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
        domain: "{{ domain.stdout }}"
        hostName: "{{ inventory_hostname }}"
        computerName: "{{ inventory_hostname }}"
      wait_for_ip_address: yes
      validate_certs: no
      state: present
    register: vmstatus

  - debug:
      msg: "Deploy message is: {{ vmstatus }}"
