---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Add DNS A record
    nsupdate:
      key_name: "{{ dns_key_name }}"
      key_secret: "{{ dns_key_secret }}"
      key_algorithm: "{{ dns_key_type }}"
      server: "{{ dns_server }}"
      zone: "{{ dns_zone }}"
      record: "{{ inventory_hostname }}"
      value: "{{ ip_address }}"
      type: "A"
      state: present
    when: not vmstatus.failed

  - name: Add DNS PTR record
    nsupdate:
      key_name: "{{ dns_key_name }}"
      key_secret: "{{ dns_key_secret }}"
      key_algorithm: "{{ dns_key_type }}"
      server: "{{ dns_server }}"
      zone: "{{ vm_zone }}."
      record: "{{ vm_arpa_name }}"
      value: "{{ inventory_hostname }}."
      type: "PTR"
      state: present
    when: not vmstatus.failed
