---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: testing
    local_action: script /usr/bin/getBestDatastores.py '{{ vcenter_host }}' '{{ cred_user }}' {{ cred_pass }}' '{{ dsfolder }}'
