---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Provision VM
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      name: "{{ inventory_hostname }}"
      folder: "{{ vmfolder }}"
      template: "template-ubuntu-16.04-64bit-8gb-v1.0"
      cluster: "{{ cluster }}"
      resource_pool: "{{ resource_pool }}"
      datacenter: "{{ datacenter }}"
      guest_id: "ubuntu64Guest"
      disk:
      - size_gb: 10
        type: "thin"
        autoselect_datastore: yes
        datastore: "{{ datastore }}"
      wait_for_ip_address: yes
      hardware:
        memory_mb: 1024
        num_cpus: 1
      networks:
      - name: "{{ network_name }}"
        ip: "{{ ip_address }}"
        device_type: "{{ device_type }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain }}"
        netmask: "{{ netmask }}"
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
      customization:
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
        domain: "{{ domain }}"
        hostName: "{{ inventory_hostname }}"
        computerName: "{{ inventory_hostname }}"
      validate_certs: no
      state: present
    register: deploy
    ignore_errors: True

  - debug:
      msg: "Deploy message is: {{ deploy }}"

  - name: Update DNS A record on success
    nsupdate:
      key_secret: "{{ dns_key_1 }}"
      server: "ns1.op-zone1.sfo1"
      zone: "op-zone1.sfo1"
      record: "ansible"
      value: "{{ ip_address }}"
      type: "A"
      state: present
    when: not deploy.failed

# - name: Determine PTR record
#   script: |
#      blah
#   |
#
# - name: Update DNS PTR record on success
#   nsupdate:
#     key_name: "nsupdate"
#     key_secret: "+bFQtBCta7j2vWkjPkAFtgA=="
#     server: "ns1.op-zone1.sfo1"
#     zone: "op-zone1.sfo1"
#     record: "ansible"
#     value: "{{ ip_address }}"
#     type: "PTR"
#     state: present
#   when: {{ deploy.failed == False }}
#
#nsupdate -k /opt/local-vco-scripts/keys/master.key.aus
#server svc01.op-zone1.aus1
#zone tnt4-zone1.aus1
#update delete prd-tnl-pk-426.tnt4-zone1.aus1
#send
#update add prd-tnl-pk-426.tnt4-zone1.aus1 3000 A 10.136.12.78
#send
#zone 136.10.in-addr.arpa
#update add 78.12.136.10.in-addr.arpa 3000 PTR prd-tnl-pk-426.tnt4-zone1.aus1
#send
#
#*****Added host*****
#Running at Fri Feb  9 01:24:35 2018
#Deleting Host - [prd-tnl-pk-356.tnt4-zone1.aus1, 10.136.12.39, /opt/local-vco-scripts/keys/master.key.aus, tnt4-zone1.aus1]
#nsupdate -k /opt/local-vco-scripts/keys/master.key.aus
#server ns1.op-zone1.aus1
#zone tnt4-zone1.aus1
#update delete prd-tnl-pk-356.tnt4-zone1.aus1 A 10.136.12.39
#send
#zone 136.10.in-addr.arpa
#update delete 39.12.136.10.in-addr.arpa PTR prd-tnl-pk-356.tnt4-zone1.aus1
#send
#
#*****Deleted Host*****
