---
- hosts: all
  gather_facts: false
  connection: local
  vars:
    state: poweredon
  tasks:
  - name: Remove DNS A record
    nsupdate:
      key_name: "{{ dns_key_name }}"
      key_secret: "{{ dns_key_secret }}"
      key_algorithm: "{{ dns_key_type }}"
      server: "{{ dns_server }}"
      zone: "{{ dns_zone }}"
      record: "{{ inventory_hostname }}"
      value: "{{ ip_address }}"
      type: "A"
    when: state == "absent"

  - name: Remove DNS PTR record
    nsupdate:
      key_name: "{{ dns_key_name }}"
      key_secret: "{{ dns_key_secret }}"
      key_algorithm: "{{ dns_key_type }}"
      server: "{{ dns_server }}"
      zone: "{{ vm_zone }}."
      record: "{{ vm_arpa_name }}"
      value: "{{ inventory_hostname }}."
      type: "PTR"
    when: state == "absent"

  - name: Shutdown VM first if delete required
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      folder: "{{ datacenter }}/vm/{{ vmfolder }}"
      name: "{{ inventory_hostname }}"
      validate_certs: no
      state: "poweredoff"
    when: state == "absent"

  - name: Set VM to desired state
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      folder: "{{ datacenter }}/vm/{{ vmfolder }}"
      name: "{{ inventory_hostname }}"
      validate_certs: no
      state: "{{ state }}"
