---
- hosts: all
  gather_facts: false
  connection: local
  vars:
    state: poweredon
  tasks:
    - name: Shutdown VM first if delete required
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        folder: "{{ datacenter }}/vm/{{ vmfolder }}"
        name: "{{ inventory_hostname }}"
        validate_certs: no
        state: "poweredoff"
      when: state == "absent"

    - name: Set VM to desired state
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        folder: "{{ datacenter }}/vm/{{ vmfolder }}"
        name: "{{ inventory_hostname }}"
        validate_certs: no
        state: "{{ state }}"
