---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Debug check1
    debug:
      msg: "host={{ inventory_hostname }} ip={{ ip_address }}"

  - name: Get reverse DNS name from IP
    command: echo "{{ ip_address | ipaddr('revdns') }}"
    register: revname

  - name: Get reverse DNS zone from IP
    shell: echo "{{ ip_address | ipaddr('revdns') }}" | cut -d'.' -f 3,4,5,6,7
    register: revzone

  - name: Debug check2
    debug:
      msg: "revname is {{ revname.stdout }} and rev zone is {{ revzone.stdout }}"

  - name: Provision VM
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      name: "{{ inventory_hostname }}"
      folder: "{{ vmfolder }}"
      template: "template-ubuntu-16.04-64bit-8gb-v1.0"
      cluster: "{{ cluster }}"
      resource_pool: "{{ resource_pool }}"
      datacenter: "{{ datacenter }}"
      guest_id: "ubuntu64Guest"
      disk:
      - size_gb: 10
        type: "thin"
        autoselect_datastore: yes
        datastore: "{{ datastore }}"
      wait_for_ip_address: yes
      hardware:
        memory_mb: 1024
        num_cpus: 1
      networks:
      - name: "{{ network_name }}"
        ip: "{{ ip_address }}"
        device_type: "{{ device_type }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain }}"
        netmask: "{{ netmask }}"
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
      customization:
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
        domain: "{{ domain }}"
        hostName: "{{ inventory_hostname }}"
        computerName: "{{ inventory_hostname }}"
      validate_certs: no
      state: present
    register: vmstatus

  - debug:
      msg: "Deploy message is: {{ vmstatus }}"

  - name: Add DNS A record
    nsupdate:
      key_name: "{{ dns_key_name }}"
      key_secret: "{{ dns_key_secret }}"
      key_algorithm: "{{ dns_key_type }}"
      server: "{{ dns_server }}"
      zone: "{{ domain }}"
      record: "{{ inventory_hostname }}"
      value: "{{ ip_address }}"
      type: "A"
      state: present
    when: not vmstatus.failed

  - name: Add DNS PTR record
    nsupdate:
      key_name: "{{ dns_key_name }}"
      key_secret: "{{ dns_key_secret }}"
      key_algorithm: "{{ dns_key_type }}"
      server: "{{ dns_server }}"
      zone: "{{ revzone.stdout }}"
      record: "{{ revname.stdout }}"
      value: "{{ inventory_hostname }}."
      type: "PTR"
      state: present
    when: not vmstatus.failed

