---
- hosts: all
  gather_facts: false
  connection: local
  vars_files:
  - "/var/lib/awx/secrets/vcenter.yml"
  - "/var/lib/awx/secrets/dns.yml"
  tasks:
  - name: Check1
    debug:
      msg: "dns_key_name is {{ dns_key_aus }} and vcenter_user is {{ vcenter_user }}"
