---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Get reverse DNS name from IP
    command: echo "{{ ip_address | ipaddr('revdns') }}"
    register: revname

  - name: Show debug output
    debug:
      msg:
       - "inventory_hostname: {{ inventory_hostname }}"
       - "ip_address: {{ ip_address }}"
       - "revname: {{ revname.stdout }}"

  - name: Show output
    debug:
      msg: "script /usr/bin/dns-add.sh {{ inventory_hostname }} {{ ip_address }} {{ revname }}"

  - name: Add DNS records
    local_action: script /usr/bin/dns-add.sh "{{ inventory_hostname }}" "{{ ip_address }}" "{{ revname }}"

