---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Gather facts about VM
    vmware_guest_facts:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      ddatacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_datacenter }}/vm/{{ vcenter_folder }}"
      name: "{{ inventory_hostname }}"
      validate_certs: no
    register: facts

  - name: Show information about VM
    debug:
      msg: "{{ facts }}"
