---
- hosts: all
  gather_facts: false
  connection: local
  vars:
    state: poweredon
  tasks:
  - name: Shutdown VM first if delete required
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      folder: "{{ vcenter_datacenter }}/vm/{{ vcenter_folder }}"
      name: "{{ inventory_hostname }}"
      validate_certs: no
      state: "poweredoff"
    when: state == "absent"

  - name: Set VM to desired state
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      folder: "{{ vcenter_datacenter }}/vm/{{ vcenter_folder }}"
      name: "{{ inventory_hostname }}"
      validate_certs: no
      state: "{{ state }}"

