---
- name: Change state of a VM
  hosts: all
  gather_facts: true
  connection: local
  tasks:
  - vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter }}"
      cluster: "{{ cluster }}"
      folder: "{{ datacenter }}/vm/{{ vmfolder }}"
      name: "{{ inventory_hostname }}"
      validate_certs: no
      state: {{ state }}
